---
test:
  stage: test
  image: ruby:3
  script:
    - bash -n scripts/fetch-and-update \
        scripts/git-commit-changes \
        scripts/generate-pages-git-branch \
        scripts/git-push-branch
    - ruby -c scripts/create-json-files

deploy:
  stage: deploy
  image: ruby:3
  variables:
    NVDCVE_DIR: nvdcve
    PAGES_BRANCH: pages
  before_script:
    - git config user.name "GitLab CI Runner"
    - git config user.email "gitlab@example.com"
  script:
    # update NVD/CVE files by fetching the last archieve
    - scripts/fetch-and-update $NVDCVE_DIR

    # commit & push changes in git history
    - scripts/git-commit-changes $NVDCVE_DIR
    - scripts/git-push-branch HEAD

    # generate & push pages branch
    - scripts/generate-pages-git-branch $PAGES_BRANCH
    - scripts/git-push-branch $PAGES_BRANCH -- -f
  only:
    - master
