---
language: ruby

jobs:
  include:
  - stage: test
    script:
    - bash -n scripts/fetch-and-update \
        scripts/git-commit-changes \
        scripts/generate-pages-git-branch \
        scripts/git-push-branch
    - ruby -c scripts/create-json-files
